import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { TaskManagementSection } from './TaskManagementSection';
import { Modal } from '../components/ui/Modal';
import { createRoadmap, listRoadmaps, updateRoadmap, updateRoadmapPhase, type Roadmap, type RoadmapPhase } from '../lib/roadmap.api';

type Status = 'Chưa bắt đầu' | 'Đang thực hiện' | 'Hoàn thành';
const statuses: Status[] = ['Chưa bắt đầu', 'Đang thực hiện', 'Hoàn thành'];
const control = { border: '1px solid #CBD5E1', background: 'white', borderRadius: 7, padding: '9px 14px', fontSize: 13, fontWeight: 600, cursor: 'pointer', color: '#0F172A' } as const;
const progressOf = (roadmap: Roadmap) => roadmap.phases.length ? Math.round(roadmap.phases.reduce((total, phase) => total + phase.progress, 0) / roadmap.phases.length) : 0;
const statusOf = (roadmap: Roadmap): Status => progressOf(roadmap) === 100 ? 'Hoàn thành' : progressOf(roadmap) > 0 ? 'Đang thực hiện' : 'Chưa bắt đầu';

export function AimPage() {
  const [roadmaps, setRoadmaps] = useState<Roadmap[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [adding, setAdding] = useState(false); const [editing, setEditing] = useState<Roadmap | null>(null); const [phaseEditing, setPhaseEditing] = useState<{ roadmapId: string; phase: RoadmapPhase } | null>(null); const [saving, setSaving] = useState(false);
  const [title, setTitle] = useState(''); const [goal, setGoal] = useState(''); const [dueDate, setDueDate] = useState(''); const [phases, setPhases] = useState(''); const [phaseProgress, setPhaseProgress] = useState(0);
  useEffect(() => { void (async () => { try { setRoadmaps(await listRoadmaps()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải lộ trình.'); } finally { setLoading(false); } })(); }, []);
  const resetForm = () => { setTitle(''); setGoal(''); setDueDate(''); setPhases(''); };
  const create = async (event: FormEvent) => { event.preventDefault(); if (!title.trim() || !goal.trim()) return; setSaving(true); setError(null); try { const created = await createRoadmap({ title: title.trim(), goal: goal.trim(), due_date: dueDate || null, phases: phases.split(/\n|,/).map(name => name.trim()).filter(Boolean).slice(0, 20).map(name => ({ name })) }); setRoadmaps(items => [created, ...items]); resetForm(); setAdding(false); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể lưu lộ trình.'); } finally { setSaving(false); } };
  const openEdit = (roadmap: Roadmap) => { setError(null); setEditing(roadmap); setTitle(roadmap.title); setGoal(roadmap.goal); setDueDate(roadmap.due_date ?? ''); };
  const saveEdit = async (event: FormEvent) => { event.preventDefault(); if (!editing || !title.trim() || !goal.trim()) return; setSaving(true); setError(null); try { const updated = await updateRoadmap(editing.id, { title: title.trim(), goal: goal.trim(), due_date: dueDate || null }); setRoadmaps(items => items.map(item => item.id === updated.id ? updated : item)); setEditing(null); resetForm(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể lưu thay đổi.'); } finally { setSaving(false); } };
  const savePhase = async (event: FormEvent) => { event.preventDefault(); if (!phaseEditing) return; setSaving(true); try { const updated = await updateRoadmapPhase(phaseEditing.roadmapId, phaseEditing.phase.id, phaseProgress); setRoadmaps(items => items.map(item => item.id !== phaseEditing.roadmapId ? item : { ...item, phases: item.phases.map(phase => phase.id === updated.id ? updated : phase) })); setPhaseEditing(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể cập nhật chặng học.'); } finally { setSaving(false); } };
  return <main style={{ minHeight: '100vh', padding: 32, boxSizing: 'border-box', background: '#F8FAFC', color: '#0F172A' }}><div style={{ display: 'grid', gap: 24 }}><TaskManagementSection />
    <section style={{ background: 'white', border: '1px solid #E2E8F0', borderRadius: 16, padding: 28 }}><div style={{ display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12 }}><div><h2 style={{ margin: 0, fontSize: 18 }}>Lộ trình & Mục tiêu</h2><p style={{ margin: '6px 0 0', color: '#64748B', fontSize: 13 }}>Bấm lộ trình để chỉnh sửa; bấm từng chặng để cập nhật tiến độ.</p></div><button onClick={() => { resetForm(); setAdding(true); }} style={{ ...control, background: '#1E3A8A', color: 'white', border: 0 }}>＋ Tạo lộ trình mới</button></div>
      {error && <p role="alert" style={{ color: '#B91C1C', fontSize: 13 }}>{error}</p>}{loading ? <p style={{ color: '#64748B' }}>Đang tải lộ trình...</p> : <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(280px, 1fr))', gap: 16, marginTop: 20, overflowX: 'auto' }}>{statuses.map(status => <div key={status} style={{ background: '#F8FAFC', borderRadius: 12, padding: 14, minHeight: 260 }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 14 }}><b>{status}</b><span style={{ color: '#64748B', fontSize: 13 }}>{roadmaps.filter(item => statusOf(item) === status).length}</span></div><div style={{ display: 'grid', gap: 12 }}>{roadmaps.filter(item => statusOf(item) === status).map(item => { const progress = progressOf(item); return <article key={item.id} onClick={() => openEdit(item)} title="Bấm để chỉnh sửa lộ trình" style={{ background: 'white', border: '1px solid #E2E8F0', borderRadius: 10, padding: 14, cursor: 'pointer' }}><b>{item.title}</b><p style={{ fontSize: 13, color: '#64748B', margin: '6px 0' }}>{item.goal}</p><small>Hạn: {item.due_date ? new Intl.DateTimeFormat('vi-VN').format(new Date(`${item.due_date}T00:00:00`)) : 'Chưa đặt hạn'}</small><div style={{ height: 7, background: '#E2E8F0', borderRadius: 20, overflow: 'hidden', margin: '12px 0 6px' }}><div style={{ height: '100%', width: `${progress}%`, background: '#10B981' }} /></div><small>{progress}% · {item.phases.filter(phase => phase.progress === 100).length}/{item.phases.length} chặng hoàn thành</small><div style={{ display: 'grid', gap: 6, marginTop: 12 }}>{item.phases.map(phase => <button key={phase.id} onClick={event => { event.stopPropagation(); setPhaseProgress(phase.progress); setPhaseEditing({ roadmapId: item.id, phase }); }} title="Bấm để cập nhật tiến độ" style={{ ...control, padding: '7px 9px', textAlign: 'left', display: 'flex', justifyContent: 'space-between' }}><span>{phase.name}</span><b>{phase.progress}%</b></button>)}</div></article>; })}</div></div>)}</div>}
    </section>
    <Modal isOpen={adding} onClose={() => !saving && setAdding(false)} title="Tạo lộ trình mới"><RoadmapForm onSubmit={create} title={title} setTitle={setTitle} goal={goal} setGoal={setGoal} dueDate={dueDate} setDueDate={setDueDate} phases={phases} setPhases={setPhases} saving={saving} submitLabel="Tạo lộ trình" onCancel={() => setAdding(false)} includePhases /></Modal>
    <Modal isOpen={Boolean(editing)} onClose={() => !saving && setEditing(null)} title="Chỉnh sửa lộ trình"><RoadmapForm onSubmit={saveEdit} title={title} setTitle={setTitle} goal={goal} setGoal={setGoal} dueDate={dueDate} setDueDate={setDueDate} phases={phases} setPhases={setPhases} saving={saving} submitLabel="Lưu thay đổi" onCancel={() => setEditing(null)} /></Modal>
    <Modal isOpen={Boolean(phaseEditing)} onClose={() => !saving && setPhaseEditing(null)} title="Cập nhật tiến độ chặng"><form onSubmit={savePhase} style={{ display: 'grid', gap: 14 }}><b>{phaseEditing?.phase.name}</b><label style={fieldLabel}>Tiến độ: {phaseProgress}%<input type="range" min="0" max="100" step="5" value={phaseProgress} onChange={event => setPhaseProgress(Number(event.target.value))} /></label><div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}><button type="button" onClick={() => setPhaseEditing(null)} disabled={saving} style={secondaryButton}>Hủy</button><button disabled={saving} style={primaryButton}>{saving ? 'Đang lưu' : 'Lưu tiến độ'}</button></div></form></Modal>
  </div></main>;
}

function RoadmapForm({ onSubmit, title, setTitle, goal, setGoal, dueDate, setDueDate, phases, setPhases, saving, submitLabel, onCancel, includePhases = false }: { onSubmit: (event: FormEvent) => void; title: string; setTitle: (value: string) => void; goal: string; setGoal: (value: string) => void; dueDate: string; setDueDate: (value: string) => void; phases: string; setPhases: (value: string) => void; saving: boolean; submitLabel: string; onCancel: () => void; includePhases?: boolean }) { return <form onSubmit={onSubmit} style={{ display: 'grid', gap: 14 }}><label style={fieldLabel}>Tên lộ trình<input autoFocus required value={title} maxLength={200} onChange={event => setTitle(event.target.value)} style={input} /></label><label style={fieldLabel}>Mục tiêu cần đạt<input required value={goal} maxLength={500} onChange={event => setGoal(event.target.value)} style={input} /></label><label style={fieldLabel}>Hạn hoàn thành<input type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} style={input} /></label>{includePhases && <label style={fieldLabel}>Các chặng (mỗi dòng một chặng)<textarea value={phases} onChange={event => setPhases(event.target.value)} rows={3} style={{ ...input, resize: 'vertical' }} /></label>}<div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}><button type="button" onClick={onCancel} disabled={saving} style={secondaryButton}>Hủy</button><button disabled={saving} style={primaryButton}>{saving ? 'Đang lưu' : submitLabel}</button></div></form>; }
const input = { padding: 10, border: '1px solid #CBD5E1', borderRadius: 7 } as const;
const primaryButton = { border: 0, borderRadius: 8, padding: '9px 14px', background: '#1E3A8A', color: 'white', fontSize: 13, fontWeight: 600, cursor: 'pointer' } as const;
const secondaryButton = { ...primaryButton, background: 'white', color: '#334155', border: '1px solid #CBD5E1' } as const;
const fieldLabel = { display: 'grid', gap: 6, color: '#334155', fontSize: 13, fontWeight: 600 } as const;
